title: The Churchill Chronicle
description: The Churchill Chronicle Magazine
url: "https://churchillchronicle.tk"

# Build settings
host: 0.0.0.0
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
compress_html:
  comments: all
